name: "${project.name}"
version: "${project.version}-${git.commit.id.abbrev}"
description: "${project.description}\nBuilt at ${git.build.time}"

author: "lhochbaum"
website: "https://github.com/lhochbaum"

main: "${project.groupId}.${project.artifactId}.${project.name}"
