name: "${project.name}"
version: "${project.version}-${git.commit.id.abbrev}"
description: "${project.description}\nBuilt at ${git.build.time}"

author: "lhochbaum"
website: "https://github.com/lhochbaum"

depend:
- PlotSquared
main: "${project.groupId}.${project.artifactId}.${project.name}"

commands:
  wand:
    description: "Erlaubt es Dir, die Wand deines Plots zu verändern."
    usage: "/wand"
    permission: "customborders.command"
    aliases:
      - "wall"
      - "pborder"
